namespace message;

public enum AJBNNHJDOEK : uint
{
	ZONE_TYPE_STABLE = 0u,
	ZONE_TYPE_PRE_SHRINK = 1u,
	ZONE_TYPE_SHRINK = 2u,
	ZONE_TYPE_RANDOM_PRESHRINK = 3u,
	ZONE_TYPE_RANDOM_SHRINK = 4u,
	ZONE_TYPE_COUNT = 5u,
	ZONE_TYPE_RANDOM_PREMOVE = 6u,
	ZONE_TYPE_RANDOM_MOVE = 7u,
	ZONE_TYPE_INVALID = 255u
}
