namespace message;

public enum AODHDBMJFKH : uint
{
	ERR_NONE,
	ERR_PARSE_MESSAGE_FAILED,
	ERR_AUTH_FAILED,
	ERR_JOIN_MATCH_FAILED,
	ERR_CONNECT_TIMEOUT,
	ERR_JOIN_MATCH_FAILED_DEAD,
	ERR_JOIN_MATCH_FAILED_MATCHEND,
	ERR_JOIN_MATCH_FAILED_MAPNOTOPEN,
	ERR_JOIN_MATCH_FAILED_RoomFull,
	ERR_START_GAME_FAILED_DRAW,
	ERR_JOIN_MATCH_FAILED_DISABLE_RECONNECT,
	ERR_JOIN_MATCH_FAILED_FRIENDOB_END,
	ERR_START_GAME_FAILED_DRAW_FOR_FRIENDOB,
	ERR_JOIN_MATCH_FAILED_CANNOT_FRIENDOB_PREVIOUS_GAME,
	ERR_JOIN_MATCH_FAILED_UGC_GS_NOT_READY,
	ERR_JOIN_MATCH_FAILED_PLAYER_MATCH_OVER,
	ERR_JOIN_MATCH_FAILED_UGC_PLAYER_AUTOSAVE
}
