namespace message;

public enum AOPDFILCONA : uint
{
	ETKGRI_ALIVE_COUNT = 1u,
	ETKGRI_WIN_SCORE,
	ETKGRI_LEADING_SCORE,
	ETKGRI_LEADING_TEAMID,
	ETKGRI_2ND_SCORE,
	ETKGRI_2ND_TEAMID,
	ETKGRI_LEADING_WINTIME,
	ETKGRI_MAX_KNIFENUM,
	ETKGRI_CURRENT_PHASE,
	ETKGRI_NB
}
