namespace message;

public enum BOKCOAKHOOI : uint
{
	ESUMMONED_COFFIN_STATE_NONE,
	ESUMMONED_COFFIN_STATE_CREATE,
	ESUMMONED_COFFIN_STATE_OPENED,
	ESUMMONED_COFFIN_STATE_DESTROY,
	ESUMMONED_COFFIN_STATE_CLOSED_BEFORE_OPEN,
	ESUMMONED_COFFIN_STATE_CLOSED_AFTER_OPEN
}
