namespace message;

public enum CHDMOIJCNNB : uint
{
	ECUSTOMROOM_TYPE_NONE = 0u,
	ECUSTOMROOM_TYPE_CASUAL = 1u,
	ECUSTOMROOM_TYPE_LEAGUE_NORMAL = 2u,
	ECUSTOMROOM_TYPE_BATCH = 6u,
	ECUSTOMROOM_TYPE_WORKSHOP = 8u,
	ECUSTOMROOM_TYPE_ESPORTS = 11u
}
