namespace message;

public enum CMDBIPLGLGA : uint
{
	EGROUPMODE_SOLO = 0u,
	EGROUPMODE_DUAL = 1u,
	EGROUPMODE_TRIPLE = 2u,
	EGROUPMODE_QUAD = 3u,
	EGROUPMODE_PENTA = 4u,
	EGROUPMODE_HEXA = 5u,
	EGROUPMODE_8 = 7u,
	EGROUPMODE_12 = 11u
}
