namespace message;

public enum DBMMHGPFEEJ : uint
{
	EPRI_ENERGYDEVICE_PHASE,
	EPRI_ENERGYDEVICE_CHARGE_PROGRESS,
	EPRI_ENERGYDEVICE_PLAYERS,
	EPRI_ENERGYDEVICE_PLAYERSAWARDED,
	EPRI_ENERGYDEVICE_NB
}
