namespace message;

public enum DLBMPCCFKKM : uint
{
	EMATCHMODE_NONE,
	EMATCHMODE_CASUAL,
	EMATCHMODE_RANKING,
	EMATCHMODE_ROOM,
	EMATCHMODE_CHAMPION,
	EMATCHNODE_TRAINNING,
	EMATCHNODE_CSRANKING,
	EMATCHMODE_CUP,
	EMATCHMODE_UGC,
	EMATCHMODE_PERIODIC,
	EMATCHMODE_UGCAllMap,
	EMATCHMODE_PVE,
	EMATCHMODE_UGCRoomMatchMaking,
	EMATCHMODE_GUILD_WAR,
	EMATCHMODE_HIPPOCRISIS_RANKING,
	EMATCHMODE_GUILD_WAR_TOURNAMENT,
	EMATCHMODE_CS_PEAK,
	EMATCHMODE_ESPORTS
}
