namespace message;

public enum FCGEACFABBM : uint
{
	EPRI_TREASURY_DOOR_ISOPENED,
	EPRI_TREASURY_ISAVAILABLE,
	EPRI_TREASURY_CHARGE_PROGRESS,
	EPRI_TREASURY_UAV_DEAD,
	EPRI_TREASURY_TeamsInTrigger,
	EPRI_TREASURY_NBOrangeFox_BREAK_DOOR,
	EPRI_TREASURY_UpgradeGem,
	EPRI_TREASURY_OPEN_WITH_RELEASE_UAV_BUFF,
	EPRI_TREASURY_ROBBED,
	EPRI_TREASURY_ROBBERTEAMID,
	EPRI_TREASURY_NB
}
