namespace message;

public enum FNGOKPJLEIJ : uint
{
	EWeaponExpansionAbilityExecutionFailReason_None,
	EWeaponExpansionAbilityExecutionFailReason_OwnerNotFound,
	EWeaponExpansionAbilityExecutionFailReason_TargetNotFound,
	EWeaponExpansionAbilityExecutionFailReason_WeaponMismatch,
	EWeaponExpansionAbilityExecutionFailReason_AbilityNotFound,
	EWeaponExpansionAbilityExecutionFailReason_AbilityTypeMismatch,
	EWeaponExpansionAbilityExecutionFailReason_NoAmmo,
	EWeaponExpansionAbilityExecutionFailReason_BeyondReach,
	EWeaponExpansionAbilityExecutionFailReason_TargetBlocked,
	EWeaponExpansionAbilityExecutionFailReason_ExecuteIntervalInvalid,
	EWeaponExpansionAbilityExecutionFailReason_RescueDart_NotTeammate,
	EWeaponExpansionAbilityExecutionFailReason_RescueDart_NotKnockdownTeammate,
	EWeaponExpansionAbilityExecutionFailReason_RescueDart_TeammateBeingRescued
}
