namespace message;

public enum FOMEJJEHHEJ : uint
{
	EDGGGRI_ALIVE_COUNT = 1u,
	EDGGGRI_WIN_SCORE,
	EDGGGRI_LEADING_SCORE,
	EDGGGRI_LEADING_TEAMID,
	EDGGGRI_2ND_SCORE,
	EDGGGRI_2ND_TEAMID,
	EDGGGRI_LEADING_WINTIME,
	EDGGGRI_WIN_TIME,
	EDGGGRI_NB
}
