namespace message;

public enum HAACEODOPFI : uint
{
	ECWBRGRI_ALIVE_PLAYERCOUNT,
	ECWBRGRI_CURRENT_PHASE,
	ECWBRGRI_DRAGONTASK_PHASE,
	ECWBRGRI_REVIVEZONE_REMAINCOUNT,
	ECWBRGRI_REVIVEZONE_CloseTimeMS,
	ECWBRGRI_IIV_FLOATINGLAND_PLAYERCOUNT,
	ECWBRGRI_NB
}
