namespace message;

public enum HCFAJFBKDIJ : uint
{
	EUAV_VISUALTYPE_NONE,
	EUAV_VISUALTYPE_EVENT,
	EUAV_VISUALTYPE_GAMEGLOBALMISSION,
	EUAV_VISUALTYPE_HEAL,
	EUAV_VISUALTYPE_CSMODE_ROUND,
	EUAV_VISUALTYPE_AIRLINE,
	EUAV_VISUALTYPE_CyberMushroomScoutUAV,
	EUAV_VISUALTYPE_BooyahBountyUAV,
	EUAV_VISUALTYPE_BooyahBountyRankingStatueUAV,
	EUAV_VISUALTYPE_IceWallBuffUAV,
	EUAV_VISUALTYPE_TreasuryRobbedUAV,
	EUAV_VISUALTYPE_HomerSkill
}
