namespace message;

public enum HHHIJHEIPLA : uint
{
	EPRI_ENERGYDEVICEPHASE_NONE,
	EPRI_ENERGYDEVICEPHASE_BEFORELANDING,
	EPRI_ENERGYDEVICEPHASE_FIRSTLANDING,
	EPRI_ENERGYDEVICEPHASE_SECONDLANDING,
	EPRI_ENERGYDEVICEPHASE_THIRDLANDING,
	EPRI_ENERGYDEVICEPHASE_IDLE,
	EPRI_ENERGYDEVICEPHASE_CHARGING,
	EPRI_ENERGYDEVICEPHASE_FINISHED
}
