namespace message;

public enum HKFBJOHPDCF : uint
{
	ECSGRI_MAX_ROUND = 1u,
	ECSGRI_CURRENT_ROUND,
	ECSGRI_CURRENT_PHASE,
	ECSGRI_MATCH_POINT,
	ECSGRI_MATCH_DRAW_STATE,
	ECSGRI_ROUND_AIRDROP_DATA_ID,
	ECSGRI_MATCH_START_BUFF,
	ECSGRI_MATCH_SCORE_EXT,
	ECSGRI_GAMEZONE_INDEX,
	ECSGRI_SPECIAL_ROUND,
	ECSGRI_GLOO_SPECIAL_ROUND,
	ECSGRI_EIGHTH_TRAIN_ROUND,
	ECSGRI_SURPRISESHOP_OPEN,
	ECSGRI_NB
}
