namespace message;

public enum IHDACHNBFNG
{
	GameObject = 0,
	Texture2D = 1,
	Mesh = 2,
	Material = 3,
	AnimationClip = 4,
	AudioClip = 5,
	SkeletonMesh = 6,
	Skeleton = 7,
	ColliderMesh = 10,
	Text = 11,
	GrassSystem = 12,
	CSV = 13,
	UIAtlas = 14,
	ABGameObjectRes = 15,
	Collider = 16,
	AnimationController = 17,
	EventAnimationClip = 18,
	Avatar = 19,
	RockSystem = 20,
	TreeSystem = 21,
	CustomPlayer = 22,
	CombineMeshRenderer = 23,
	NaveMesh = 24,
	Particles = 25,
	Timeline = 26,
	PlayableController = 27,
	Other = 29,
	Folder = 30,
	PhysicalMaterial = 31,
	Plot = 32,
	PlotActor = 33,
	HudTemplate = 34,
	BlockTemplate = 35,
	Localization = 36
}
