namespace message;

public enum INFAJFHPPPK : uint
{
	EELECTRICGIRL_ED_MINIPAWN_STATE_NONE,
	EELECTRICGIRL_ED_MINIPAWN_STATE_ADD,
	EELECTRICGIRL_ED_MINIPAWN_STATE_FIRE,
	EELECTRICGIRL_ED_MINIPAWN_STATE_DESTROY
}
