namespace message;

public enum JJKGBAKMNDI : uint
{
	EITEM_TYPE_MEDKIT,
	EITEM_TYPE_GRENADE,
	EITEM_TYPE_GRENADE_FLASH,
	EITEM_TYPE_GRENADE_SMOKINGBOMB,
	EITEM_TYPE_LOADOUT_CAREPACKAGE,
	EITEM_TYPE_LOADOUT_CAMPFIRE,
	EITEM_TYPE_LOADOUT_TREASUREMAP,
	EITEM_TYPE_BUILDING,
	EITEM_TYPE_LANDMINE,
	EITEM_TYPE_BOUNTY_SCANNER,
	EITEM_TYPE_LOADOUT_BOUNTYCONTRACT,
	EITEM_TYPE_MINISENTRY,
	EITEM_TYPE_PAINTSPRAYER,
	EITEM_TYPE_DUMMY,
	EITEM_TYPE_BOMBMODE_PLIERS,
	EITEM_TYPE_FIREWORKS,
	EITEM_TYPE_JUMPPAD,
	EITEM_TYPE_TELESCOPE,
	EITEM_TYPE_HAND_CATAPULT,
	EITEM_TYPE_PERSONAL_SHOP,
	EITEM_TYPE_PERSONAL_TELEPORTDOOR,
	EITEM_TYPE_GRENADE_FROZEN,
	EITEM_TYPE_GRENADE_DEICEWALL,
	EITEM_TYPE_GRENADE_MULTIEXPLOSIVE,
	EITEM_TYPE_LOADOUT_MAP_SMOKE,
	EITEM_TYPE_LOADOUT_MAP_CAMP_FIRE,
	EITEM_TYPE_LOADOUT_MAP_SPACE_SHIELD,
	EITEM_TYPE_ALL
}
