namespace message;

public enum JKFJLCPMMAE : uint
{
	EWWGRI_CURRENT_PHASE = 1u,
	EWWGRI_CURRENT_POINT,
	EWWGRI_CIVILWIN_POINT,
	EWWGRI_CURRENT_WOLF_COUNT,
	EWWGRI_ALL_WOLF_COUNT,
	EWWGRI_WOLF_KILLCD,
	EWWGRI_WOLF_SKILLCD,
	EWWGRI_VoteCenter_CDEndTime,
	EWWGRI_GameEndTime,
	EWWGRI_GameOverFlag,
	EWWGRI_NB
}
