namespace message;

public enum JPEOBBKALLB : uint
{
	EPHYSXSTATE_WALKING,
	EPHYSXSTATE_FALLING,
	EPHYSXSTATE_PARACHUTING,
	EPHYSXSTATE_ONBOARD,
	EPHYSXSTATE_SKYDIVING,
	EPHYSXSTATE_HITFLY,
	EPHYSXSTATE_SWIMMING,
	EPHYSXSTATE_ONSTROP,
	EPHYSXSTATE_FOOTBALL,
	EPHYSXSTATE_JETFLY,
	EPHYSXSTATE_GLIDING,
	EPHYSXSTATE_ONGRAPPLINGHOOK,
	EPHYSXSTATE_SKATEBOARDING,
	EPHYSXSTATE_ONFERRISWHEEL,
	EPHYSXSTATE_FLIGHTROAM,
	EPHYSXSTATE_FAITHJUMPING,
	EPHYSXSTATE_SWING,
	EPHYSXSTATE_FORCEMOVING,
	EPHYSXSTATE_SPRINT,
	EPHYSXSTATE_SlideRunning,
	EPHYSXSTATE_SlideFalling,
	EPHYSXSTATE_PASSIVEMOVING,
	EPHYSXSTATE_COUNT
}
