namespace message;

public enum KDJNLHBBCKP : uint
{
	EBLOODPOOLORB_STATE_NONE,
	EBLOODPOOLORB_STATE_INVINCIBLE,
	EBLOODPOOLORB_STATE_HIGH,
	EBLOODPOOLORB_STATE_MID,
	EBLOODPOOLORB_STATE_LOW,
	EBLOODPOOLORB_STATE_DESTROY
}
