namespace message;

public enum KIICBDFPCHE
{
	UGCLANGUAGE_Unknown,
	UGCLANGUAGE_ENGLISH,
	UGCLANGUAGE_SIMPLIFIED_CHINESE,
	UGCLANGUAGE_TRADITIONAL_CHINESE,
	UGCLANGUAGE_THAI,
	UGCLANGUAGE_VIETNAMESE,
	UGCLANGUAGE_INDONESIA,
	UGCLANGUAGE_BRAZILIAN_PORTUGUESE,
	UGCLANGUAGE_SPANISH,
	UGCLANGUAGE_RUSSIAN,
	UGCLANGUAGE_KOREAN,
	UGCLANGUAGE_FRENCH,
	UGCLANGUAGE_GERMAN,
	UGCLANGUAGE_TURKISH,
	UGCLANGUAGE_HINDI,
	UGCLANGUAGE_JAPANESE,
	UGCLANGUAGE_ROMANIAN,
	UGCLANGUAGE_ARABIC,
	UGCLANGUAGE_BURMESE,
	UGCLANGUAGE_URDU,
	UGCLANGUAGE_BENGALI,
	UGCLANGUAGE_MALAY
}
