namespace message;

public enum KJDFEOIPCFM : uint
{
	ETRAININGGAME_ZONE_PLAYERCOUNT,
	ETRAININGGAME_QUEUE_PLAYERCOUNT,
	ETRAININGGAME_MAX_KILL_CHANGE,
	ETRAININGGAME_FOOTBALLGAME_PHASE,
	ETRAININGGAME_FOOTBALLGAME_RECENTSCORERID,
	ETRAININGGAME_FOOTBALLGAME_SCORES,
	ETRAININGGAME_FOOTBALLGAME_OPEN,
	ETRAININGGAME_IIV_FLOATINGLAND_PLAYERCOUNT,
	ETRAININGGAMEGRI_NB
}
