namespace message;

public enum KMAOAMNKGKL : uint
{
	EPRI_VEHICLE_CUR_HP,
	EPRI_VEHICLE_MAX_HP,
	EPRI_VEHICLE_IS_STABLE,
	EPRI_VEHICLE_SHAPE,
	EPRI_VEHICLE_ParachuteState,
	EPRI_VEHICLE_AirDropState,
	EPRI_VEHICLE_SKINID,
	EPRI_VEHICLE_BRAKESTATE,
	EPRI_VEHICLE_HORNSTATE,
	EPRI_VEHICLE_LEVEL,
	EPRI_VEHICLE_ENGINE,
	EPRI_VEHICLE_CHIP_AND_ENABLE,
	EPRI_VEHICLE_PILOT_MODE,
	EPRI_VEHICLE_SAP_MUSIC,
	EPRI_VEHICLE_UPGRADE_ROUTEID,
	EPRI_VEHICLE_ROUTE_TOKEN,
	EPRI_VEHICLE_ADDITIONAL_MAX_SPEED_RATE,
	EPRI_VEHICLE_CHANGE_SPEED_ZONE_RATE,
	EPRI_VEHICLE_AUTO_USE_ROUTE_TOKEN_TIME,
	EPRI_VEHICLE_IS_INVINCIBLE,
	EPRI_VEHICLE_TARGET_VEHICLEID,
	EPRI_VEHICLE_ISINLOCK,
	EPRI_VEHICLE_HEALSTATE,
	EPRI_VEHICLE_NB
}
