namespace message;

public enum LIBAPJGFPLP : uint
{
	EGiantGRI_AliveCount = 1u,
	EGiantGRI_Phase,
	EGiantGRI_EquipSet,
	EGiantGRI_MAX_ROUND,
	EGiantGRI_CURRENT_ROUND,
	EGiantGRI_TIMING_ON,
	EGiantGRI_MILLSTONEINDEX,
	EGiantGRI_EFFECTIVE_DEFENDER,
	EGiantGRI_EFFECTIVE_ATTACKER,
	EGiantGRI_CURRENT_DISTANCE,
	EGiantGRI_TOTAL_DISTANCE,
	EGiantGRI_LAST_TEAM_SCORE,
	EGiantGRI_ZONE_INDEX,
	EGiantGRI_NB
}
