namespace message;

public enum MOJHJCNBGOG : uint
{
	ERR_JOINROOM_NONE,
	ERR_JOINROOM_FULL,
	ERR_JOINROOM_ALLOW,
	ERR_JOINROOM_CLOSE,
	ERR_JOINROOM_DYING,
	ERR_JOINROOM_NOTEXIST,
	ERR_JOINROOM_WAITINGOPENED,
	ERR_JOINROOM_INCONSISTENTGAMEMODEORTYPE
}
