namespace message;

public enum NALFNCKIBNP : uint
{
	ECoinBonusType_Init = 0u,
	ECoinBonusType_Kill = 1u,
	ECoinBonusType_Win = 2u,
	ECoinBonusType_Lose = 3u,
	ECoinBonusType_LoseStreak_2 = 4u,
	ECoinBonusType_LoseStreak_3 = 5u,
	ECoinBonusType_Purchase = 6u,
	ECoinBonusType_KillBonusWithNamedWeapon = 7u,
	ECoinBonusType_FirstBlood = 8u,
	ECoinBonusType_Giant_Attack = 9u,
	ECoinBonusType_Giant_Defence = 10u,
	ECoinBonusType_Giant_KnowDown = 11u,
	ECoinBonusType_DeadInSafeZonePenalty = 12u,
	ECoinBonusType_ExplodeBomb = 13u,
	ECoinBonusType_RemoveBomb = 14u,
	ECoinBonusType_InvBonusCoin = 15u,
	ECoinBonusType_Buff = 16u,
	ECoinBonusType_Metro_Arrest = 17u,
	ECoinBonusType_Metro_MiniGame = 18u,
	ECoinBonusType_Metro_Gym = 19u,
	ECoinBonusType_Metro_Unlock = 20u,
	ECoinBonusType_Metro_Treasure = 21u,
	ECoinBonusType_Skill = 22u,
	ECoinBonusType_Metro_Draw = 23u,
	ECoinBonusType_Metro_Mission = 24u,
	ECoinBonusType_Metro_Salary = 25u,
	ECoinBonusType_Metro_Deliver = 26u,
	ECoinBonusType_Metro_UGC = 27u,
	ECoinBonusType_NoRecord = 28u,
	ECoinBonusType_BattleLevel_KillHigherLevel = 29u,
	ECoinBonusType_WithdrawalRefund = 30u,
	ECoinBonusType_RoundFirstKnockDown = 31u,
	ECoinBonusType_AuroraItemGenerator = 32u,
	ECoinBonusType_SensorBeaconHost = 33u,
	ECoinBonusType_SensorBeacon_KillInRange = 34u,
	ECoinBonusType_CybermushroomCoin = 35u,
	ECoinBonusType_KingSword_KillFromKing = 36u,
	ECoinBonusType_KingSword_KillTheKing = 37u,
	ECoinBonusType_SeaFoodLittleGirl = 38u,
	ECoinBonusType_CSDelayAddCoinFromRoundResult = 39u,
	ECoinBonusType_CSRefundMushroomCost = 40u,
	ECoinBonusType_Debug = 99999u
}
