namespace message;

public enum NMCBIHOOFFF : uint
{
	ESTARTFIRESTATE_NONE,
	ESTARTFIRESTATE_READY,
	ESTARTFIRESTATE_FIRE,
	ESTARTFIRESTATE_CHARGE,
	ESTARTFIRESTATE_CANCEL,
	ESTARTFIRESTATE_WARMUP,
	ESTARTFIRESTATE_COMBINED_DOUBLE_FIRE,
	ESTARTFIRESTATE_COMBINED_LEFT_FIRE,
	ESTARTFIRESTATE_WEAPON_ABILITY_START,
	ESTARTFIRESTATE_WEAPON_ABILITY_END
}
