namespace message;

public enum OHEABAIFMEP : uint
{
	EBOOYAHBOUNTY_COIN_TYPE_NONE,
	EBOOYAHBOUNTY_COIN_TYPE_KILL,
	EBOOYAHBOUNTY_COIN_TYPE_HELP,
	EBOOYAHBOUNTY_COIN_TYPE_MOVE,
	EBOOYAHBOUNTY_COIN_TYPE_TREASURE,
	EBOOYAHBOUNTY_COIN_TYPE_SEARCH,
	EBOOYAHBOUNTY_COIN_TYPE_EXPLODE,
	EBOOYAHBOUNTY_COIN_TYPE_OPERATE,
	EBOOYAHBOUNTY_COIN_TYPE_ICEWALL
}
