namespace message;

public enum PIBGLGOJEKE : uint
{
	EKNOCKDOWN_SHIELD_STATE_NONE,
	EKNOCKDOWN_SHIELD_STATE_CREATE,
	EKNOCKDOWN_SHIELD_STATE_REMAIN,
	EKNOCKDOWN_SHIELD_STATE_HIDE,
	EKNOCKDOWN_SHIELD_STATE_DESTROY
}
