namespace COW.GamePlay;

internal class IDOLFDOLKMA
{
	protected CFOOJHNKDOH JOOENGNHJMD;

	protected ArrayMap<CFOOJHNKDOH> LLFDJMGMICL;

	public JFGEEHILLNP NKPFAEIGJLB;

	public IDOLFDOLKMA(JFGEEHILLNP LDCIMNAAGNO)
	{
	}

	public void PKJDACNJAKH(ELEOLIDMFDJ NBEHKLPMFIG, FOIMHIENJIB DJAPBCKDFKA)
	{
	}

	public void PKFDPKMHPAB(ELEOLIDMFDJ NBEHKLPMFIG, bool IDCHCEECMBE = false)
	{
	}

	public void IJALCKKJPMN(CFOOJHNKDOH GKKELMDDGBJ)
	{
	}

	public void AAJBLNPFLOB(float OKJIFBCMDAD, float HOGHEFNINAE)
	{
	}

	public void BAKAJEDKGCI(float OKJIFBCMDAD, float HOGHEFNINAE)
	{
	}

	public ELEOLIDMFDJ ELLMANJCBHA()
	{
		return ELEOLIDMFDJ.Idle;
	}

	public void JJNMDNMKJOH(ELEOLIDMFDJ NBEHKLPMFIG)
	{
	}
}
