using UnityEngine;

namespace COW.GamePlay;

internal interface IGABMLHFICJ
{
	bool GCAPCLOFHAG();

	OKEAMEELLBB KPAKJFPCKGC();

	void GILKIBOMHNC(Vector3 GNNGFJMJOIL, FDAEPHMIEPC PJMDKPKBBAM);

	void CFHKNNGLPLD(Vector3 HJKAFKBMBFO, FDAEPHMIEPC PJMDKPKBBAM);

	Quaternion JIHEBEJDDLB(Quaternion EILAAKIBIBM, Quaternion MJHGBLMFJND, FDAEPHMIEPC PJMDKPKBBAM, out bool GPKDOONOLLB);

	void EAGEHCCLICN();

	bool CPPJAHABGOI();

	bool ABGNNBFDDIP(Vector3 HGMCAKCJGPB);

	float GNACEPONDOB();
}
