using GCommon;
using TsiU;
using UnityEngine;

namespace COW.GamePlay;

internal class JKLFGKHLKDH : TBTActionLeaf
{
	internal class PCHMDNPBBLJ
	{
		public MAGKGOBAPMA FEHFAOPEANN;

		public JEIDAGGMFMM KMPDKMHJKMM;

		public DJNDCPIHGHC NHNOIINKJAL;

		public PKBGDFAMKBC IJLGBKBAINM;

		public PFPIAAGLJMJ MDLNKOMAIPC;

		public LJOIACILBOL CDIEMIJPJBH;

		public OOIOMMEHALD DKNIAHAIING;

		public HAKEDAKEGPC KHKOHDGIANH;

		public BPNJMMMDONI JPPMJCFHKML;

		public CJMKFELBJCB BMLALMBPPIO;

		public PJAKBEKHEDH IGAMJBEAOGG;

		public DCPKKPFKKKO AALNHEHFANK;

		public FHKFJFGBMCM NJOHMADMJAB;

		public FEGHCEJHHIC EHLOEKJBHDK;

		public EOKGEKNGBPC PMLOLLAGNIP;

		public DGLMBKLDCJI OPJNCOHLBIA;

		public CAPBGOHPJNN EMMGKJMHPBH;

		public GKHBMGLILDK CCDMLDBAAAC;

		public NPFJLCKKKGI JMOBNNGALBH;

		public AGIBJJLIACL OOOCANBOLHH;

		public FCBBEHPCPEG IJOPOOMENIB;

		public OGFIMMIMHBN LLNGMAAPEIO;

		public BGPBKPOOEGM PIGDNCLFPBK;

		public JBLPAOPLPIN IMDOHMFMNNK;

		public FMOCHGEEKIO EFFOKDGBBPN;

		public HFOOCOACMBJ MMMNOPPJPLB;

		public DIELLPLNKAB ELJOBPBMAOD;

		public MDNFGNMBIGP MDNFGNMBIGP;

		public FPNEFDOBGIO FPNEFDOBGIO;

		public LBFADLBNCMK EHENONCHDAE;

		public FHNGHFJIBLP LOKPAPNAAGA;

		public BNBMAHJFLLB EAIGFNPBHAH;

		public APKHMLBDLBK LHMHFLLLAEB;

		public DOKNFJEJAGP JFGNNCLDPPE;

		public KAJNPHHIGCF JLHIDDININJ;

		public FLIDKCMGKIP JMKOKBHGNGE;

		public MGDFJODMIMH MEEKEAFJNDG;

		public HAEIOKJOCBE PDEJJMPAOIC;

		public KCNDIMONFFD ADOGDNKJNEB;

		public KIHNDIJHMOD GLHBDDEGIMJ;
	}

	protected Camera JBDFGKDBIGM;

	protected Camera HMPGFIFIJFI => null;

	private bool MFJFEOIIKFN(Player KDJNEHDAAFL, UserControlHandler JOMLNJLCKEE)
	{
		return false;
	}

	protected void KDCAEFJENMC(Player KDJNEHDAAFL, UserControlHandler JOMLNJLCKEE, ANFOAEIIBCM LOHDBKGGMGA)
	{
	}

	private bool NFOOJGELFMB(FDAEPHMIEPC LENHJOBNPOI, Player KDJNEHDAAFL)
	{
		return false;
	}

	protected void ELIBIGHOJFF(Player KDJNEHDAAFL, UserControlHandler JOMLNJLCKEE, ANFOAEIIBCM LOHDBKGGMGA, bool LBNLKOEGLNH)
	{
	}

	private static bool OGICKKEBAMG(UserControlHandler JOMLNJLCKEE)
	{
		return false;
	}

	private static void NINPEMGCCPH(Player PGEGMKJKOKI, FDAEPHMIEPC KEDHIAANLGO)
	{
	}
}
