namespace COW.GamePlay;

public enum OALEGBJOANK
{
	SUCCESS,
	SPAWN_POS_COUNT_NOT_MATCH,
	NO_TARGET_POINT_FOUND,
	NO_MUST_MODE_ITEMS,
	ALL_TEAM_SPAWN_POINT_NUM_NOT_MATCH,
	SINGLE_TEAM_SPAWN_POINT_NOT_MATCH,
	SINGLE_TEAM_SPAWN_POINT_NUM_NOT_MATCH
}
