namespace COW.GamePlay;

public interface ONFBHNEPBCM
{
	void PCCMKALCBDG(BHGGAEEHJCO JFPADHMCADP, byte LIKPJDHGPFG, bool LOIEMCDAKAO);

	bool CJBBCKDHNLN(uint DLIDCCDEMEL);

	bool CAMLOHBFEMH(uint DLIDCCDEMEL, uint LBAGGCIOPOA, BHGGAEEHJCO OBMFMAKFDDL);

	void IMAGEFCDKDC(BHGGAEEHJCO OBMFMAKFDDL, byte PGEKLFOGMOI, byte LJFOFELODNB);

	void GNLPHANDMHE(BHGGAEEHJCO OBMFMAKFDDL);

	uint POBPBEHIFHI(uint PNILAGJNOPJ, BHGGAEEHJCO OBMFMAKFDDL);
}
