namespace FFVoice;

public enum FFMagicVoiceEvent
{
	FFMV_EVENT_SETUSERINFO = 0,
	FFMV_EVENT_UPDATETOKEN = 1,
	FFMV_EVENT_UPDATED_EFFECT_LIST = 3,
	FFMV_EVENT_GET_FREE_VIP = 4,
	FFMV_EVENT_UPDATE_SOUND_EFFECT_BAG_LIST = 5,
	FFMV_EVENT_UPDATE_SOUND_EFFECT_BAG_BUYED_STATUS = 6,
	FFMV_EVENT_UPDATE_SOUND_EFFECT_BAG_LIST_BUYED_INFO = 7,
	FFMV_EVENT_DOWNLOAD_SOUND_EFFECT_START = 8,
	FFMV_EVENT_DOWNLOAD_SOUND_EFFECT_PROGRESS = 9,
	FFMV_EVENT_DOWNLOAD_SOUND_EFFECT_PREPARED = 10,
	FFMV_EVENT_PLAY_SOUND_EFFECT = 11,
	FFMV_EVENT_NOTIFY_TOKEN_NEAR_EXPIRE = 12,
	FFMV_EVENT_DELETE_DOWNLOADED_SOUND_EFFECT = 13,
	FFMV_EVENT_PLAY_SOUND_EFFECT_PARAM = 20,
	FFMV_EVENT_CHECK_FREE_FOR_LIMIT_TIME_BUY_ID = 21,
	FFMV_EVENT_START_PREVIEW_MAGIC_VOICE_EFFECT = 101,
	FFMV_EVENT_START_AUDIO_DETECT = 102
}
