namespace FFVoice;

public enum FFVoiceAIAgentInterruptReason
{
	AIAGENT_INTERRUPT_REASON_UNKNOWN,
	AIAGENT_INTERRUPT_REASON_VOICE,
	AIAGENT_INTERRUPT_REASON_FORCE,
	AIAGENT_INTERRUPT_REASON_SERVER
}
