namespace FFVoice;

public enum FFVoice_RTC_SERVER_REGION
{
	RTC_US_SERVER = 2,
	RTC_SG_SERVER = 3,
	RTC_KR_SERVER = 4,
	RTC_AU_SERVER = 5,
	RTC_DE_SERVER = 6,
	RTC_BR_SERVER = 7,
	RTC_IN_SERVER = 8,
	RTC_JP_SERVER = 9,
	RTC_IE_SERVER = 10,
	RTC_USW_SERVER = 11,
	RTC_USM_SERVER = 12,
	RTC_CA_SERVER = 13,
	RTC_LON_SERVER = 14,
	RTC_FRA_SERVER = 15,
	RTC_DXB_SERVER = 16,
	RTC_BD_SERVER = 201,
	RTC_EXT_SERVER = 10000,
	RTC_DEFAULT_SERVER = 10001
}
