namespace FFVoice;

public enum FFVoiceAIAgentStatus
{
	AIAGENT_STATUS_UNKNOWN,
	AIAGENT_STATUS_JOINED,
	AIAGENT_STATUS_LISTENNING,
	AIAGENT_STATUS_THINKING,
	AIAGENT_STATUS_INTERRUPTED,
	AIAGENT_STATUS_SPEAKING,
	AIAGENT_STATUS_SPEAK_OVER,
	AIAGENT_STATUS_EXCEPTION
}
