namespace GCommon;

public enum ETraceRouteError
{
	CMD_STATUS_SUCCESSFUL,
	CMD_STATUS_FAILED,
	CMD_STATUS_USER_STOP,
	CMD_STATUS_ERROR,
	CMD_STATUS_NETWORK_ERROR,
	CMD_STATUS_ERROR_UNKNOW_HOST,
	CMD_STATUS_ERROE_NULL_RESULT
}
