namespace GCommon;

public enum ResFileType
{
	None = -1,
	Compulsory,
	OptionalCloth,
	OptionalVoice,
	OptionalLoc,
	OptionalMap,
	OptionalMap1,
	OptionalPet,
	OptionalWerewolves,
	OptionalRushB,
	OptionalRushingPets,
	OptionalMapMax,
	OptionalMap2,
	OptionalLudo,
	OptionalFullScreenCG,
	OptionalMap4,
	OptionalAvatar,
	OptionalLobbyResource,
	OptionalUGC,
	OptionalTraining,
	OptionalLoneWolf,
	OptionalLoneWolfStrikeOut,
	OptionalNewBlast,
	OptionalMapHippo,
	OptionalInfection,
	OptionalSingersB,
	OptionalSocial,
	OptionalFootball,
	OptionalSnowDuel,
	OptionalHuntingGround,
	OptionalInGameRes,
	CustomUGC,
	AudioWem,
	OptionalMapPony,
	ExtraSoFile,
	OptionalWeRun,
	OptionalUGCOldParadise,
	OptionalMultiRegion
}
