namespace proto;

public class EEventPush
{
	public enum EventPushType
	{
		EventPushType_NONE,
		EventPushType_OFFLINEGROUPINVITE_BUDDY,
		EventPushType_OFFLINEGROUPINVITE_MENTOR,
		EventPushType_OFFLINEGROUPINVITE_STUDENT,
		EventPushType_GROUPREMIND_CAPTAIN_START,
		EventPushType_GROUPREMIND_MEMBER_READY,
		EventPushType_OFFLINEFRIENDS_VETERAN_ONLINE,
		EventPushType_OFFLINEVETERANS_FRIEND_ONLINE,
		EventPushType_GROUPREMIND_RETURN_TO_LOBBY,
		EventPushType_PURCHASE_CLAN_PRIVILEGE,
		EventPushType_SECURE_MAILBOX_APPLY,
		EventPushType_SECURE_MAILBOX_UNBINDING,
		EventPushType_SECURE_MAILBOX_BINDING,
		EventPushType_ESPORTS_ROUND_START,
		EventPushType_BIGEVENT_TREASURE_HUNT,
		EventPushType_ESPORTS_CHECKIN
	}
}
