namespace proto;

public class EGameServer
{
	public enum Proto
	{
		Proto_NONE = 0,
		Proto_START_GAMESERVER = 1,
		Proto_UGC_DEBUG_START = 2,
		Proto_JOIN_GAMESERVER = 3,
		Proto_NOTI_DROP_MATCH = 8,
		Proto_NOTI_PUNISH_PLAYER = 9,
		Proto_NOTI_HIPPO_ABANDONMATCH = 10,
		Proto_CROSS_MAP_MATCHMAKING_SUSS = 11,
		Proto_CROSS_MAP_MATCHMAKING_FAILED = 12,
		Proto_SOCIALHALL_UPDATE_CLOTHES = 13,
		Proto_SOCIALHALL_SELECT_PROFILE = 14,
		Proto_SOCIALHALL_CHOOSE_GAME_BAG_SHOW = 15,
		Proto_SOCIALHALL_CHOOSE_EMOTE = 16,
		Proto_SOCIALHALL_CHOOSE_HEAD_PIC = 17,
		Proto_SOCIALHALL_CHOOSE_BANNER = 18,
		Proto_SOCIALHALL_CHOOSE_SLOTS = 19,
		Proto_SOCIALHALL_CHOOSE_SHOW = 20,
		Proto_SOCIALHALL_CHOOSE_COLLECTION_ACTIONS = 21,
		Proto_SOCIALHALL_CHOOSE_PIN = 22,
		Proto_SOCIALHALL_CHOOSE_SUPER_EMOTE = 23,
		Proto_SOCIALHALL_CLAIMED_DANCE_TITLE = 24,
		Proto_SOCIALHALL_CHOOSE_TITLE = 25,
		Proto_SOCIALHALL_UPDATE_ARENA_INFO = 26,
		Proto_SOCIALHALL_UPDATE_DANCE_INFO = 27,
		Proto_SOCIALHALL_UPDATE_COLLECTION_CUSTOM_LIST = 28,
		Proto_SOCIALHALL_MODIFY_NICKNAME = 29,
		Proto_SOCIALHALL_UPDATE_SHARED_SET = 30,
		Proto_SOCIALHALL_PRIVILEGE_ITEM_UPDATE = 31,
		Proto_SOCIALHALL_CLAIMED_ARENA_TITLE = 32
	}

	public enum ServerStatus
	{
		ServerStatus_NONE,
		ServerStatus_RUNNING,
		ServerStatus_SOFTCLOSED,
		ServerStatus_DOWN,
		ServerStatus_OVERLOADED
	}

	public enum ServerType
	{
		ServerType_NONE,
		ServerType_NORMAL,
		ServerType_UGC,
		ServerType_UGC_DEBUG,
		ServerType_FE_DEBUG,
		ServerType_SOCIAL_HALL
	}

	public enum AIType
	{
		AIType_NONE = 0,
		AIType_CCS = 1,
		AIType_NOVA = 101
	}
}
