namespace proto;

public class EMail
{
	public enum Source
	{
		Source_GAME,
		Source_ADMIN,
		Source_EVENT
	}

	public enum ActionType
	{
		ActionType_ATTACHMENT,
		ActionType_NOTICE,
		ActionType_CLAN_INVITE,
		ActionType_TRANSLATE
	}

	public enum Type
	{
		Type_NONE = 0,
		Type_CLAN_INVITE = 1,
		Type_CLAN_DISMISS = 2,
		Type_CLAN_KICKOUT = 3,
		Type_CLAN_REASSIGN_CAPTAIN = 4,
		Type_RANKING_SEASON_REWARDS = 5,
		Type_RANKING_RANK_LEVEL_REWARDS = 6,
		Type_EP_UNLOCK_REWARD = 7,
		Type_EP_CHALLENGE_REWARD = 8,
		Type_STORE_SEND_GIFT = 9,
		Type_GLOBAL_DROPS = 10,
		Type_CLAN_RACE_AWARD = 11,
		Type_SET_STREAMER = 14,
		Type_DEL_STREAMER = 15,
		Type_INSTANT_GAME_REWARD = 16,
		Type_SUBSCRIPTION_EP = 17,
		Type_CHAMPIONSHIP_TEAM_DISMISS = 18,
		Type_CHAMPIONSHIP_TEAM_KICKOUT = 19,
		Type_CHAMPIONSHIP_TRIAL_REWARDS = 20,
		Type_GOP_PURCHASE = 21,
		Type_NEWBIE_RETURN = 22,
		Type_CLAN_REGION_CHANGE = 23,
		Type_VETERAN_RETURN = 24,
		Type_RANKING_SEASON_TOP_REWARDS = 25,
		Type_NEW_PALYER_UNCLAIM_REWARDS = 26,
		Type_FRESH_UNCLAIM_REWARDS = 27,
		Type_EP_DAILY_QUEST_UNCLAIM_REWARDS = 28,
		Type_CS_RANKING_RANK_LEVEL_REWARDS = 29,
		Type_CS_RANKING_SEASON_REWARDS = 30,
		Type_CS_RANKING_HANGUP_WARN = 31,
		Type_CS_RANKING_HANGUP_BAN = 32,
		Type_CLAN_DEPUTY_CAPTAIN_NOTIFY = 33,
		Type_LIMITEDEVENT_LEADERBOARD_REWARDS = 34,
		Type_INTIMACY_AWARDS = 35,
		Type_SKINHACK = 36,
		Type_CS_RANKING_SEASON_TOP_REWARDS = 37,
		Type_CLAN_WAR_ACCOUNT_REWARDS = 38,
		Type_VIPCARD_WEEKLY_REWARD = 39,
		Type_VIPCARD_MONTHLY_REWARD = 40,
		Type_VIPCARD_MONTHLY_WEEKLY_REWARD = 41,
		Type_VIPCARD_SVIP_REWARD = 42,
		Type_VIPCARD_SVIP_WEEKLY_REWARD = 43,
		Type_VIPCARD_SVIP_MONTHLY_REWARD = 44,
		Type_VIPCARD_SVIP_MONTHLY_WEEKLY_REWARD = 45,
		Type_MSHOP_RECHARGE_NOTIFY = 46,
		Type_PERIODIC_RANKING_RANK_LEVEL_REWARDS = 47,
		Type_PERIODIC_RANKING_SEASON_REWARDS = 48,
		Type_CHUMMY_INTIMACY_REWARDS = 49,
		Type_LIMITED_EVENT_SETTLE_REWARDS = 50,
		Type_GOOGLE_PLAY_POINT = 51,
		Type_VETERAN_REWARDS = 52,
		Type_ANTIHACK_MATCH_BANNED1 = 53,
		Type_ANTIHACK_MATCH_BANNED2 = 54,
		Type_ANTIHACK_MATCH_BANNED3 = 55,
		Type_WORKSHOP_CODE_BANNED = 57,
		Type_EP_DAILY_PROCESS_UNCLAIM_REWARDS = 58,
		Type_BP_SEND_PREMUIM_PASS = 59,
		Type_DELIVER_REBATE_CARD_INSTANT = 60,
		Type_DELIVER_REBATE_CARD_DELAY = 61,
		Type_PREVETERAN_REWARDS = 62,
		Type_EQUIP_SPECIAL_FRIEND_SKILL_AWARD = 63,
		Type_PVE_LEADERBOARD_AWARD = 64,
		Type_CREDITSCORE_WELL_BEHAVIOR_AWARD = 65,
		Type_DATASTORAGE_LEADERBOARD_AWARD = 66,
		Type_CLAN_CLAN_ACTIVENESS = 67,
		Type_BR_FIRST_RANK_REWARD = 68,
		Type_CS_FIRST_RANK_REWARD = 69,
		Type_CLAN_PERSONAL_ACTIVENESS = 70,
		Type_CLAN_REMIND_LOW_ACTIVENESS = 71,
		Type_BIGEVENT_LOCAL_MAIL = 73,
		Type_UGC_AUTHOR_REWARD = 74,
		Type_UPLOAD_DEBUGGERLOG_STEPS = 75,
		Type_CLAN_REMIND_LOW_ACTIVENESS_MEMBER = 76,
		Type_BR_WIN_PASS_RWARD_TYPE_0 = 77,
		Type_CS_WIN_PASS_RWARD_TYPE_0 = 78,
		Type_BR_WIN_PASS_RWARD_TYPE_1 = 79,
		Type_CS_WIN_PASS_RWARD_TYPE_1 = 80,
		Type_STORE_SEND_GIFT_NO_INTIMACY = 81,
		Type_WORKSHOP_CODE_SOFT_BANNED = 82,
		Type_WORKSHOP_RENEW_VIP_FAILED = 83,
		Type_WORKSHOP_RENEW_VIP_SUCCESS = 84,
		Type_RECEIVE_OUTDATE_REWARDS = 85,
		Type_HIPPO_WAREHOUSE_FULL = 86,
		Type_CLAN_PRIVILEGE = 87,
		Type_CLAN_PRIVILEGE_EXTEND = 88,
		Type_CLAN_APPOINT_CAPTAIN = 89,
		Type_ACCOUNT_NEW_ROLE = 90,
		Type_PRIME_STORE_SEND_GIFT = 91,
		Type_CREATE_PUNISH_MATCH_BEHAVIOR = 92,
		Type_CREATE_PUNISH_CHAT_REPORT = 93,
		Type_WORKSHOP_COVER_PERMISSION_LIMITED_TIME = 94,
		Type_WORKSHOP_COVER_PERMISSION_PERMANT = 95,
		Type_WORKSHOP_COVER_PERMISSION_REVOKE = 96,
		Type_BIGEVENT_RESEND_REWARDS = 97,
		Type_CREDITSCORE_SUMMARY_LV_CHANGE = 98,
		Type_GUILD_WAR_HACKER_PUNISHMENT = 99,
		Type_CS_DDOS_COMPENSATION = 100,
		Type_BR_DDOS_COMPENSATION = 101,
		Type_DELETE_CS_PEAK_AWARD = 102,
		Type_DELETE_CS_PEAK_TITLE = 103,
		Type_NCOLOR25B_RECEIVE_OUTDATE_COLLECTION_REWARDS = 104,
		Type_ESPORTS_APPROVED = 105,
		Type_ESPORTS_REJECTED = 106,
		Type_ESPORTS_INVITE = 107,
		Type_ESPORTS_LEADERBOARD_IN_GAME_AWARD = 108,
		Type_ESPORTS_LEADERBOARD_EXTERNAL_AWARD = 109,
		Type_ESPORTS_ABORT = 110,
		Type_ESPORTS_SPONSOR_AWARD_REFUND = 111,
		Type_TEAM_TOP_UP_UNCLAIMED_AWARDS = 112,
		Type_ESPORTS_ANTIHACK = 113,
		Type_CLAN_PUNISH_RENAME = 114,
		Type_CLAN_PUNISH_CLEAR_SLOGAN = 115,
		Type_CLAN_PUNISH_DISMISS = 116,
		Type_RELAY_MART_UNCLAIMED_REBATE = 117,
		Type_NEWBIE_PRESET_MAKE_UP = 118,
		Type_ANTIADDICTION_APPLY_BIND = 119,
		Type_ANTIADDICTION_GUARDIAN_UNBIND = 120,
		Type_ANTIADDICTION_CHILDREN_UNBIND = 121,
		Type_ANTIADDICTION_ACCEPT_BIND = 122,
		Type_ANTIADDICTION_CHILDREN_APPLY_UNBIND = 123,
		Type_WORKSHOP_SHORT_CODE_GENERATE = 124,
		Type_RESOURCE_STORE_EXPANSION = 125,
		Type_VIPCARD_RENEWAL_LOCAL_MAIL = 126,
		Type_TOPUP_EVENT_UNCLAIMED_REWARDS = 127,
		Type_SHARED_GACHA_UNCLAIM_COLLECT_REWARDS = 128,
		Type_UGC_MONETIZE_REFUND = 129,
		Type_UGC_MONETIZE_CLAWBACK = 130
	}

	public enum Status
	{
		Status_INIT,
		Status_PROCESSED,
		Status_DELETED
	}

	public enum ReportMailType
	{
		ReportMailType_NONE = 0,
		ReportMailType_REPORTER_FEEDBACK = 1,
		ReportMailType_OFFENDER_PUNISH = 2,
		ReportMailType_BAN_GROUP_MATCH_FEEDBACK = 3,
		ReportMailType_BAN_RANKING_MATCH_FEEDBACK = 4,
		ReportMailType_BAN_LEADERBOARD_RANKING_FEEDBACK = 5,
		ReportMailType_RESET_CSRANK_FEEDBACK = 6,
		ReportMailType_RESET_BRRANK_FEEDBACK = 7,
		ReportMailType_PERMANENT_BAN_ACCOUNT_FEEDBACK = 8,
		ReportMailType_TIMELIMITED_BAN_ACCOUNT_FEEDBACK = 9,
		ReportMailType_BAN_LEADERBOARD_SWIPING_SCORE_PUNISH = 10,
		ReportMailType_BAN_GROUP_MATCH_SWIPING_SCORE_PUNISH = 11,
		ReportMailType_TEAMMATE_PUNISHMENT_FEEDBACK = 12,
		ReportMailType_VOICE_PUNISH = 13,
		ReportMailType_VOICE_WARN = 14,
		ReportMailType_VOICE_PUNISH_SECOND = 15,
		ReportMailType_VOICE_FEEDBACK_UNIVERSAL_TEMPLATE = 16,
		ReportMailType_REPORTER_FEEDBACK_PENDING = 17,
		ReportMailType_CUSTOM_18 = 18,
		ReportMailType_CUSTOM_19 = 19,
		ReportMailType_CUSTOM_20 = 20,
		ReportMailType_CUSTOM_21 = 21,
		ReportMailType_CUSTOM_22 = 22,
		ReportMailType_CUSTOM_23 = 23,
		ReportMailType_CUSTOM_24 = 24,
		ReportMailType_CUSTOM_25 = 25,
		ReportMailType_CUSTOM_26 = 26,
		ReportMailType_CUSTOM_27 = 27,
		ReportMailType_CUSTOM_28 = 28,
		ReportMailType_CUSTOM_29 = 29,
		ReportMailType_CUSTOM_30 = 30,
		ReportMailType_REDUCE_EXEMPTION_NTF = 31,
		ReportMailType_DETECTED_BEHAVIORS_FEEDBACK = 32,
		ReportMailType_GUILDWAR_PUNISH = 33,
		ReportMailType_VOICE_FEEDBACK = 34,
		ReportMailType_REPORTER_COMPENSATED_FEEDBACK = 35,
		ReportMailType_PHOTOWALL_PUNISH = 36,
		ReportMailType_API_REPORTER_FEEDBACK = 99
	}

	public enum Platform
	{
		Platform_GENERAL,
		Platform_IOS,
		Platform_GOOGLEPLAY,
		Platform_HUAWEI,
		Platform_XIAOMI,
		Platform_TRIAL
	}

	public enum VisitorFilter
	{
		VisitorFilter_ALL,
		VisitorFilter_NOT_VISITOR,
		VisitorFilter_VISITOR
	}

	public enum MailMainType
	{
		MailMainType_COMMON,
		MailMainType_REPORT
	}
}
