namespace proto;

public enum TopUpTeamJoinReason
{
	TUTJR_CREATE,
	TUTJR_FRIEND_INVITE_WHISPER,
	TUTJR_FRIEND_INVITE_GAME_ASSISTANT,
	TUTJR_FRIEND_INVITE_MAIN_PAGE,
	TUTJR_FAST_JOIN_TEAM,
	TUTJR_QR_CODE,
	TUTJR_TEAM_CODE,
	TUTJR_WORLD_CHANNEL,
	TUTJR_CLAN_CHANNEL,
	TUTJR_WHISPER_CHANNEL,
	TUTJR_RECOMMEND_TEAM,
	TUTJR_AUTO_JOIN,
	TUTJR_RETURN_TO_TEAM
}
