namespace proto;

public enum Trea25BErrorCode
{
	T25BEC_SUCCESS,
	T25BEC_GRID_IS_OPENED,
	T25BEC_TARGET_BE_HELPED_COUNT_NOT_ENOUGH,
	T25BEC_MINING_BY_OTHER_FRIEND,
	T25BEC_GOLDENSHOVEL_NOT_ENOUGH,
	T25BEC_MAP_FINISHED,
	T25BEC_INVALID_DATA
}
