namespace COW;

public enum EFriendAddFrom
{
	None = 0,
	Recommended = 1,
	GameResult = 3,
	Team = 4,
	ObserverGame = 5,
	Callback = 6,
	Room = 7,
	Training = 8,
	Chat = 9,
	Clan = 10,
	Profile = 11,
	BigEvent = 12,
	DriftBottle = 13,
	GameResultRecommend = 14,
	Social = 15,
	LuckyBuff = 16,
	LeadinPlatformFriends = 17,
	SeasonReplay = 18,
	CabinWaitingPhase = 19,
	UGCPlay = 20,
	Visitor = 21,
	Maybeknow = 22,
	GameAssist = 23,
	CommonFriendMochaAccsRecommend = 24,
	CommonFriendMochaLabelRecommend = 25,
	PrecisiousSearch = 26,
	TeamScoreBoard = 27,
	QRCode = 28,
	WebViewFestival = 29,
	Gift = 30,
	RelayMartPurchaseAutoAddFriend = 31,
	RelayMartRebateAddFriend = 32,
	SquadTreasure = 33,
	Nearby = 34,
	UGCSocial = 35,
	NewBeeSocialWillingness = 36,
	NewBeeBooyahTogether = 37,
	NewBeeSavedMe = 38,
	NewBeeMatchTogether = 39,
	NewBeeNearbyPlayer = 41,
	LobbySocialArea = 42,
	LobbySocialLWResult = 43,
	Rematch = 44
}
