namespace COW;

public enum EMatchEventGroup
{
	MATCHEVENT_GROUP_NONE = 0,
	MATCHEVENT_GROUP_KILL = 1,
	MATCHEVENT_GROUP_KNOCKDOWN = 2,
	MATCHEVENT_GROUP_DAMAGE = 4,
	MATCHEVENT_GROUP_REVIVE = 8,
	MATCHEVENT_GROUP_DEAD = 0x10,
	MATCHEVENT_GROUP_ASSIST = 0x20,
	MATCHEVENT_GROUP_NORMAL_KILL = 0x40,
	MATCHEVENT_GROUP_NORMAL_KNOCKDOWN = 0x80,
	MATCHEVENT_GROUP_SAFEZONE = 0x20000000,
	MATCHEVENT_GROUP_ROUND = 0x40000000
}
