namespace COW;

public enum EventTabType
{
	NONE = 0,
	DAILY = 1,
	FESTIVAL1 = 2,
	FESTIVAL2 = 3,
	GWBINGO = 4,
	GWTOKEN = 5,
	MEGA_EVENT = 6,
	GWCommon_EVENT = 7,
	GWAD = 8,
	ACTIVENESS = 9,
	CHRIST_COSPLAY = 10,
	CHRIST_TASK = 11,
	CHRIST_LOGINREWARD = 12,
	RAMPAGE = 13,
	FESTIVAL3 = 14,
	RELEASE_NOTES = 15,
	RETURN_FEATURES = 16,
	ANNOUNCEMEN = 17,
	ESPORTS = 18,
	ALL = 999
}
