namespace COW;

public interface IUIHippoCrisisDragResponseController
{
	HippoCrisisDragOperationResult HippoCrisisDragResponseCB(HippoCrisisDragSourceInfo hippoCrisisDragSourceInfo, EDragReleaseResponseAreaType areaType);
}
