namespace AnoSDKNamespace;

public enum GCNPPHCMLKH
{
	ACE_LOCALE_CN = 1,
	ACE_LOCALE_EN = 2,
	ACE_LOCALE_RU = 3,
	ACE_LOCALE_US = 4,
	ACE_LOCALE_EU = 5,
	ACE_LOCALE_IN = 6,
	ACE_LOCALE_JP = 7,
	ACE_LOCALE_KR = 8,
	ACE_LOCALE_TW = 9,
	ACE_LOCALE_VN = 10,
	ACE_LOCAL_GLOBAL = 998,
	ACE_LOCAL_OTHERS = 999
}
