namespace UMA;

public enum EBaseSlot
{
	None = 0,
	Base_Female_Hair = 1,
	Base_Female_Head_ingame = 2,
	Base_female_Feet = 3,
	Base_female_Leg = 4,
	Base_female_Chest = 5,
	Base_female_Chest_1 = 6,
	Base_female_Leg_1 = 7,
	Base_female_Chest_N = 8,
	Base_female_Chest_N_1 = 9,
	Base_female_Leg_N = 10,
	Base_female_Leg_N_1 = 11,
	Base_lobby_Female_Head_N = 12,
	Base_lobby_Female_Hair_N = 13,
	Base_female_Feet_N = 14,
	Base_male_Chest_1 = 15,
	Base_male_Chest = 16,
	Base_male_Feet = 17,
	Base_male_Head = 18,
	Base_male_Hair = 19,
	Base_male_Leg = 20,
	Base_male_Leg_1 = 21,
	Base_male_Chest_N_1 = 22,
	Base_male_Chest_N = 23,
	Base_male_Feet_N = 24,
	Base_male_Hair_N = 25,
	Base_male_Head_N = 26,
	Base_male_Leg_N = 27,
	Base_male_Leg_N_1 = 28,
	Max = Base_male_Leg_N_1,
	Count = 29,
	Start = Base_Female_Hair,
	Limit = 31,
	AllBits = 536870911,
	HeadBits = 67375108
}
