namespace tcp;

public class EFriend
{
	public enum Proto
	{
		Proto_NONE,
		Proto_REQUEST_NTF,
		Proto_CONFIRM_NTF,
		Proto_REMOVE_NTF,
		Proto_RELATED_FRIEND_ONLINE,
		Proto_RELATED_FRIEND_REQUEST_NTF,
		Proto_RELATED_FRIEND_CONFIRM_NTF,
		Proto_RELATED_FRIEND_DECLINE_NTF,
		Proto_RELATED_FRIEND_REQUEST_EXPIRE_NTF,
		Proto_INTIMACY_CHANGE_NTF,
		Proto_VETERAN_FRIEND_ONLINE_NTF,
		Proto_INTIMACY_VALUE_UPDATE_NTF,
		Proto_CALLBACK_TASK_UPDATE_NTF,
		Proto_RETURNER_CALLBACK_UPDATE_NTF,
		Proto_FRIEND_ONLINE_NTF,
		Proto_CALLBACK_INVITE_NTF,
		Proto_CALLBACK_POINT_UPDATE_NTF,
		Proto_CALLBACK_ACCEPT_INVITE_NTF
	}

	public enum ErrCode
	{
		ErrCode_SUSS
	}
}
