namespace tcp;

public class EGroup
{
	public enum Proto
	{
		Proto_NONE,
		Proto_CREATE,
		Proto_INVITE,
		Proto_INVITE_NTF,
		Proto_ACCEPT,
		Proto_REFUSE,
		Proto_JOIN_NTF,
		Proto_LEAVE,
		Proto_LEAVE_NTF,
		Proto_START,
		Proto_START_NTF,
		Proto_STOP,
		Proto_STOP_NTF,
		Proto_DISMISS_NTF,
		Proto_GROUPINFO,
		Proto_READY,
		Proto_READY_NTF,
		Proto_CHANGE,
		Proto_CHANGE_NTF,
		Proto_JOINROOM,
		Proto_SPECTATEROOM,
		Proto_SHOWEMOTE,
		Proto_SHOWEMOTE_NTF,
		Proto_SHOWPETACTION,
		Proto_SHOWPETACTION_NTF,
		Proto_CHECKPLAYER,
		Proto_ANTIADDICTION_NFT,
		proto_TEAMMATEHEATING_NFT,
		Proto_CHANGEMAP_NTF,
		Proto_CHANGEAVAILABLEMAPS,
		Proto_CHANGEAVAILABLEMAPS_NTF,
		Proto_GETGROUPCODE,
		Proto_GETGROUPCODE_NTF,
		Proto_JOIN,
		Proto_JOINREQUEST_NTF,
		Proto_KICKOUT,
		Proto_CHANGEPUBPVT,
		Proto_CHANGEPUBPVT_NTF,
		Proto_ACCEPTJOIN,
		Proto_CSRANKINGBAN_NTF,
		Proto_GROUPBAN_NTF,
		Proto_RANKINGBAN_NTF,
		Proto_SYNCPATCHOPTIONALRESSTATUS,
		Proto_SYNCPATCHOPTIONALRESSTATUS_NTF,
		Proto_ACCEPTJOIN_NTF,
		Proto_START_ROOM_MATCHMAKING,
		Proto_STOP_ROOM_MATCHMAKING,
		Proto_START_ROOM_MATCHMAKING_NTF,
		Proto_STOP_ROOM_MATCHMAKING_NTF,
		Proto_CREATE_ROOM,
		Proto_REFUSE_NTF,
		Proto_REMIND,
		Proto_REMINDEE_NTF,
		Proto_REMINDER_NTF,
		Proto_CHECKINGROUPPLAYER,
		Proto_MIGRATE_GROUP,
		Proto_MIGRATE_GROUP_NTF,
		Proto_TRANSFER_LEADER,
		Proto_TRANSFER_LEADER_NTF,
		Proto_TEAMINGRANKLIMIT_NTF,
		Proto_CREDITPUNISH_NTF,
		Proto_RESERVATIONSHOW_ACCEPT,
		Proto_RESERVATIONSHOW_REMOVE,
		Proto_RESERVATIONSHOW_NTF,
		Proto_SHOWDOUBLEEMOTE,
		Proto_SHOWDOUBLEEMOTE_NTF,
		Proto_RECRUIT,
		Proto_GET_RECRUIT_LIST,
		Proto_RECRUIT_LIST_NTF,
		Proto_RECRUIT_QUICK_JOIN,
		Proto_RECRUIT_STOP,
		Proto_RECRUIT_NTF,
		Proto_RECRUIT_GET_INFO,
		Proto_RECRUIT_STOP_NTF,
		Proto_SHOWBOOYAHDAY24B_DIMENSION,
		Proto_SHOWBOOYAHDAY24B_DIMENSION_NTF,
		Proto_HIPPO_EQUIP_INFO,
		Proto_APPLY_SET_SHARE,
		Proto_APPLY_SET_SHARE_NTF,
		Proto_APPROVE_SET_SHARE_APPLY,
		Proto_APPROVE_SET_SHARE_APPLY_NTF,
		Proto_OFFER_SET_SHARE,
		Proto_OFFER_SET_SHARE_NTF,
		Proto_ACCEPT_SET_SHARE_OFFER,
		Proto_ACCEPT_SET_SHARE_OFFER_NTF,
		Proto_TAKE_OFF_SET_SHARE,
		Proto_TAKE_OFF_SET_SHARE_NTF,
		Proto_CREDIT_PUNISH_OTHER_NTF,
		Proto_SHOW_TRANSFORM_EMOTE,
		Proto_SHOW_TRANSFORM_EMOTE_NTF,
		Proto_SHOW_SF50B_CAREER_EMOTE,
		Proto_SHOW_SF50B_CAREER_EMOTE_NTF,
		Proto_LW_PLAYER_LOGOUT_GAMESERVER_NTF,
		Proto_MIGRATE_MEMBERS,
		Proto_MERGE_NTF,
		Proto_MERGE_SUCCESS_NTF,
		Proto_CHANGE_DISPLAY_STATE,
		Proto_CHANGE_DISPLAY_STATE_NTF,
		Proto_SPECTATE,
		Proto_CHANGE_UGC_SOCIAL_URL,
		Proto_GET_NEWBIE_RECRUIT_TEAM,
		Proto_NEWBIE_RECRUIT_TEAM_NTF,
		Proto_JOIN_HACKER_GROUP,
		Proto_RECRUIT_HANGUP_REPORT,
		Proto_ACCOUNT_RECRUIT_BANNED,
		Proto_RECRUIT_REMOVED_NTF
	}

	public enum ErrCode
	{
		ErrCode_SUSS = 0,
		ErrCode_GROUPEXISTED = 1,
		ErrCode_NOGROUP = 2,
		ErrCode_ALREADYINVITED = 3,
		ErrCode_NOTINVITED = 4,
		ErrCode_REACHMAXINVITEE = 5,
		ErrCode_ALREADYINGROUP = 6,
		ErrCode_NOTINGROUP = 7,
		ErrCode_REACHMAXMEMBER = 8,
		ErrCode_GROUPINGAME = 9,
		ErrCode_GROUPNOTINGAME = 10,
		ErrCode_CANNOTINVITESELF = 11,
		ErrCode_CANNOTINVITEOTHERREGION = 12,
		ErrCode_GROUPNOTREADY = 13,
		ErrCode_INVALIDGROUPMODE = 14,
		ErrCode_AUTOGROUPTIMEOUT = 15,
		ErrCode_NOSUCHPOOL = 16,
		ErrCode_CREATEGROUPFAIL = 17,
		ErrCode_INVALIDRANDOMMAPCONFIG = 18,
		ErrCode_INVITEEALREADYINGROUP = 19,
		ErrCode_INVITEEALREADYINROOM = 20,
		ErrCode_INVITEEALREADYINGAME = 21,
		ErrCode_INVITEEALREADYOFFLINE = 22,
		ErrCode_INVALIDEMOTE = 23,
		ErrCode_RANKINGMATCHLEVELLIMIT = 24,
		ErrCode_NEGATIVEGEMS = 25,
		ErrCode_ANTIADDICTIONBAN = 26,
		ErrCode_NOTCHAMPIONTEAMMEMBER = 27,
		ErrCode_INVITERNOTINGROUP = 28,
		ErrCode_INVALIDCHAMPIONTEAM = 29,
		ErrCode_NOTQUALIFIEDFORCHAMP = 30,
		ErrCode_INVITEEALREADYINTRAINING = 31,
		ErrCode_NOTQUALIFIEDFORTRAIN = 32,
		ErrCode_MAPINVALIDFORSOMEMEMBERS = 33,
		ErrCode_NOTQUALIFIEDFORGENGROUPCODE = 34,
		ErrCode_NOTQUALIFIEDFORUSEGROUPCODE = 35,
		ErrCode_NOAVAILABLEGROUPCODE = 36,
		ErrCode_NOTGROUPCAPTAIN = 37,
		ErrCode_DIFFERENTGROUPS = 38,
		ErrCode_ALREADYINMATCHMAKING = 39,
		ErrCode_CANNOTJOINSELF = 40,
		ErrCode_CANNOTJOINOTHERREGION = 41,
		ErrCode_JOINNONEXISTENTGROUP = 42,
		ErrCode_PRIVATEGROUP = 43,
		ErrCode_CANNOTKICKSELF = 44,
		ErrCode_CREATEPLAYERFAIL = 45,
		ErrCode_SELFNOTREADY = 46,
		ErrCode_JOINERALREADYINGROUP = 47,
		ErrCode_CSRANKINGBANNED = 48,
		ErrCode_RANKINGMATCHREGISTERTIMELIMIT = 49,
		ErrCode_GROUPSECRETCODENOTMATCH = 50,
		ErrCode_GROUPNOTIDLEFORBIDCHANGEMODE = 51,
		ErrCode_NOTQUALIFIEDFORCUP = 52,
		ErrCode_INVALIDCUPTEAM = 53,
		ErrCode_NOTCUPTEAMMEMBER = 54,
		ErrCode_INVALIDWORKSHOPCODE = 56,
		ErrCode_INVALIDCREDITSCORE = 57,
		ErrCode_SOMEONEDIDNOTDOWNLOADMAP = 58,
		ErrCode_PLAYERMAPINVALID = 59,
		ErrCode_KICKEDPLAYER = 60,
		ErrCode_INVALIDINVITE = 61,
		ErrCode_TEAMINGRANKRULELIMIT = 62,
		ErrCode_INVITEEALREADYINSOCIALAREA = 63,
		ErrCode_GROUPISNOTIDLE = 64,
		ErrCode_NOTGROUPLEADER = 65,
		ErrCode_NOTINROOMMATCHMAKING = 66,
		ErrCode_ALREADYINROOM = 67,
		ErrCode_INVITEEINMATCHMAKING = 68,
		ErrCode_REMINDEENOTINGROUP = 69,
		ErrCode_SelectBuildSystemInGame = 70,
		ErrCode_HACKERCANNOTJOINGROUP = 71,
		ErrCode_CANNOTJOINHACKERGROUP = 72,
		ErrCode_HACKERCANNOTINVITE = 73,
		ErrCode_TARGETNOTINGROUP = 74,
		ErrCode_MIGRAGEGROUPFAIL = 75,
		ErrCode_GROUPISFROZEN = 76,
		ErrCode_LEAVEORIGINALGROUPFAILED = 77,
		ErrCode_GROUPHASCANDIDATE = 78,
		ErrCode_OTHERPLAYERNOGROUP = 79,
		ErrCode_GUILDWARINVALID = 80,
		ErrCode_INVALIDREQUESTER = 81,
		ErrCode_DOUBLEEMOTEINVITERNOTINGROUP = 82,
		ErrCode_DOUBLEEMOTEINVITEENOTINGROUP = 83,
		ErrCode_RECRUITMEMBERNOTALLOWPOST = 84,
		ErrCode_RECRUITREACHMAXTAGNUM = 85,
		ErrCode_RECRUITTAGIDNOTFOUND = 86,
		ErrCode_RECRUITINVALIDRANKLIMIT = 87,
		ErrCode_RECRUITNOTOPEN = 88,
		ErrCode_RECRUITQUICKJOINFAILED = 89,
		ErrCode_RECRUITMEMBERNOTALLOWSTOP = 90,
		ErrCode_RECRUITGROUPMODESOLO = 91,
		ErrCode_RECRUITINVALIDGROUPSTATE = 92,
		ErrCode_ACCEPTINVITEINVALIDRECRUITCODE = 93,
		ErrCode_RECRUITTEAMNOTFOUND = 94,
		ErrCode_RECRUITQUICKJOINCUP = 95,
		ErrCode_INVITEEINDONOTDISTURB = 96,
		ErrCode_INVITEEINMATCHMAKINGBLACKLIST = 97,
		ErrCode_INVITERINMATCHMAKINGBLACKLIST = 98,
		ErrCode_UNAVAILABLEGAMEMODE = 99,
		ErrCode_HIPPOCRISISINGAMESERVER = 100,
		ErrCode_TOURNAMENTINVALID = 101,
		ErrCode_INVALIDGROUPQRCODE = 102,
		ErrCode_CANNOTSHARETOSELF = 103,
		ErrCode_SHARERPRIVILEGEINVALID = 104,
		ErrCode_SHAREENOREMAINTIMES = 105,
		ErrCode_REQUESTSHARETOOFREQUENTLY = 106,
		ErrCode_SHARERISWEARINGSHAREDSET = 107,
		ErrCode_INVALIDSHAREREQUEST = 108,
		ErrCode_INVALIDMAPVERSION = 109,
		ErrCode_CREDITPUNISHMATCHBEHAVIOR = 110,
		ErrCode_HIPPOCRISISBAGCAPACITY = 111,
		ErrCode_SELFCREDITPUNISHMATCHBEHAVIOR = 112,
		ErrCode_ACCEPTINVITEBYRECRUITRANKINVALID = 113,
		ErrCode_CSPEAKNOTQUALIFIED = 114,
		ErrCode_CSPEAKINVALID = 115,
		ErrCode_GAMEMODEPLAYCOUNTEXCEEDED = 116,
		ErrCode_RECRUITHANGUPBAN = 117
	}

	public enum LeaveReason
	{
		LeaveReason_NORMAL,
		LeaveReason_OFFLINE,
		LeaveReason_DROPMATCH,
		LeaveReason_ALLJOINROOM,
		LeaveReason_SOLOJOINROOM,
		LeaveReason_KICKOUT,
		LeaveReason_MERGEGROUP,
		LeaveReason_TIMEOUT
	}

	public enum PlayerState
	{
		PlayerState_IDLE,
		PlayerState_MATCHMAKING,
		PlayerState_INGAME,
		PlayerState_AUTOGROUP,
		PlayerState_INROOM,
		PlayerState_ROOMMATCHMAKING
	}

	public enum PlayerDisplayState
	{
		PlayerDisplayState_NONE,
		PlayerDisplayState_INGAME,
		PlayerDisplayState_SPECTATE,
		PlayerDisplayState_INRESULT
	}

	public enum State
	{
		State_IDLE,
		State_MATCHMAKING,
		State_INGAME,
		State_AUTOGROUP,
		State_INROOM,
		State_ROOMMATCHMAKING,
		State_IDLE_INGAME_MIXED
	}

	public enum PlayerPatchOptionalResStatus
	{
		PlayerPatchOptionalResStatus_NONE,
		PlayerPatchOptionalResStatus_LACK,
		PlayerPatchOptionalResStatus_START
	}

	public enum CreateFromType
	{
		CreateFromType_NONE,
		CreateFromType_OWNSELF,
		CreateFromType_GROUP,
		CreateFromType_RESERVATION
	}

	public enum JoinFromType
	{
		JoinFromType_NONE,
		JoinFromType_GROUP,
		JoinFromType_RESERVATION
	}

	public enum InviteChannelType
	{
		InviteChannelType_PLAYER,
		InviteChannelType_WORLD,
		InviteChannelType_GUILD,
		InviteChannelType_JOIN,
		InviteChannelType_RECRUITQUICKJOIN,
		InviteChannelType_RECRUIT,
		InviteChannelType_TEAMCODE,
		InviteChannelType_DEEPLINK,
		InviteChannelType_SOCIAL_RECOMMEND,
		InviteChaneelType_QRCODE,
		InviteChannelType_INGAMERESULT,
		InviteChannelType_LOBBYTOINGAME,
		InviteChannelType_NEARBY,
		InviteChannelType_SOCIAL_HALL,
		InviteChannelType_NEWBIE_CHANNEL,
		InviteChannelType_NEWBIE_RECRUIT,
		InviteChannelType_RECRUIT_HANGUP,
		InviteChannelType_AFTER_ADD_FRIEND
	}

	public enum InviteeType
	{
		InviteeType_NONE,
		InviteeType_FRIEND,
		InviteeType_GUILD,
		InviteeType_MATCHGROUP,
		InviteeType_MATCHKILLER,
		InviteeType_MATCHCHICKEN,
		InviteeType_CHAMPIONSHIP,
		InviteeType_REVENGER,
		InviteeType_CUP,
		InviteeType_RESERVATION,
		InviteeType_MATCHMVP,
		InviteeType_RECOMMENDATION,
		InviteeType_RECENTINTERACTIONS,
		InviteeType_RECENTTEAMMATE,
		InviteeType_LASTGAMETEAMMATE,
		InviteeType_INVITEONLINEVETERAN,
		InviteeType_OFFLINE,
		InviteeType_SOCIAL_RECOMMEND,
		InviteeType_SOCIAL_RECOMMEND_MOCHA_LABELS,
		InviteeType_INGAMERESULT,
		InviteeType_NEARBY,
		InviteeType_LOBBYTOINGAME,
		InviteeType_SOCIAL_HALL,
		InviteeType_AFTER_ADD_FRIEND
	}

	public enum PubPvtStatus
	{
		PubPvtStatus_NONE,
		PubPvtStatus_PUBLIC,
		PubPvtStatus_PRIVATE
	}

	public enum RoomType
	{
		Type_NONE,
		Type_CASUAL,
		Type_LEAGUE_NORMAL,
		Type_LEAGUE_OFFICIAL,
		Type_CHAMPIONSHIP,
		Type_LEAGUE_ULTIMATE,
		Type_LEAGUE_BATCH,
		Type_WEREWOLVES,
		Type_WORKSHOP,
		Type_RUSHING_PETS,
		Type_CLAN
	}

	public enum RemindType
	{
		RemindType_NONE,
		RemindType_CAPTAIN_START,
		RemindType_MEMBER_READY,
		RemindType_RETURN_TO_LOBBY
	}

	public enum DoubleEmoteBehavior
	{
		Behavior_NONE,
		Behavior_INVITE,
		Behavior_CANCEL,
		Behavior_REFUSE,
		Behavior_ACCEPT,
		Behavior_CONFIRM
	}

	public enum StopReason
	{
		StopReason_NORMAL,
		StopReason_CANCEL,
		StopReason_OFFLINE
	}

	public enum RecruitListType
	{
		RecruitListType_AUTO_REFRESH,
		RecruitListType_MANUAL_REFRESH
	}
}
