namespace tcp;

public class ERoom
{
	public enum Proto
	{
		Proto_NONE,
		Proto_ROOMLIST,
		Proto_CREATE,
		Proto_JOIN,
		Proto_SPECTATE,
		Proto_JOIN_NTF,
		Proto_LEAVE,
		Proto_LEAVE_NTF,
		Proto_DISMISS_NTF,
		Proto_KICK,
		Proto_KICK_NTF,
		Proto_START,
		Proto_ROOMINFO,
		Proto_CHANGE,
		Proto_CHANGE_NTF,
		Proto_DROPOMATCH,
		Proto_MATCHMAKINGSUSS_NTF,
		Proto_ROOMSTATE_NTF,
		Proto_CHECKINGAMEPLAYER,
		Proto_CLEARINGAMEPLAYER,
		Proto_SWITCHSEAT,
		Proto_SWITCHSEAT_NTF,
		Proto_INVITE,
		Proto_INVITE_NTF,
		Proto_SETREADY,
		Proto_SETREADY_NTF,
		Proto_REAL_CREATE,
		Proto_ADMIN_SET_ICON,
		Proto_ADMIN_DISMISS_ROOM,
		Proto_ANTIADDICTION_NFT,
		proto_TEAMMATEHEATING_NFT,
		Proto_ADMIN_GET_CUSTOMROOM_MATCHSTATS,
		Proto_ROOM_CREATE_RULE,
		Proto_CHANGEAVAILABLEMAPS,
		Proto_CHANGEAVAILABLEMAPS_NTF,
		Proto_EMULATORCHECK_NTF,
		proto_OWNERSWITCHGROUP,
		proto_OWNERSWITCHGROUP_NTF,
		Proto_ROLECHECK_NTF,
		Proto_COUNTDOWN,
		Proto_COUNTDOWN_NTF,
		Proto_CREDITSCORECHECK_NTF,
		Proto_SYNCPATCHOPTIONALRESSTATUS,
		Proto_SYNCPATCHOPTIONALRESSTATUS_NTF,
		Proto_CHECKAVAILABLEMAPS_NTF,
		Proto_WORKSHOP_LOADING_TIMEOUT,
		Proto_ADMIN_SET_ROOM_PRIORITY,
		Proto_ADMIN_CREATE,
		Proto_ADMIN_START,
		Proto_OPEN_ROOM_MATCHMAKING,
		Proto_CLOSE_ROOM_MATCHMAKING,
		Proto_START_SOLO_ROOM_MATCHMAKING,
		Proto_CANCEL_SOLO_ROOM_MATCHMAKING,
		Proto_START_GROUP_ROOM_MATCHMAKING,
		Proto_CANCEL_GROUP_ROOM_MATCHMAKING,
		Proto_OPEN_ROOM_MATCHMAKING_NTF,
		Proto_CLOSE_ROOM_MATCHMAKING_NTF,
		Proto_NO_MATCHMAKING_ROOM_NTF,
		Proto_ADMIN_GET_ROOM_LIST_POOL,
		Proto_ADMIN_GET_ROOM_MM_POOL,
		Proto_ADMIN_DEL_ROOM_LIST_POOL,
		Proto_ADMIN_DEL_ROOM_MM_POOL,
		Proto_ROOM_MATCHMAKING_TIMEOUT_NTF,
		Proto_LEVELCHECK_NTF,
		Proto_REMIND,
		Proto_REMINDEE_NTF,
		Proto_REMINDER_NTF,
		Proto_PUNISH_IN_GAME_PLAYER,
		Proto_NOT_IN_CLAN,
		Proto_GS_PREPARE_INFO,
		Proto_ADMIN_GET_ROOM_INFO_BY_ROOM_ID,
		Proto_GET_ROOM_PLAYER_PRESET_BY_ROOM_ID,
		Proto_ADMIN_GET_PLAYER_INFO,
		Proto_SPECTATE_INGAME_PLAYER,
		Proto_AFK_PUNISH_NTF,
		Proto_APPLYJOIN_NTF,
		Proto_REFUSE,
		Proto_REFUSE_NTF,
		Proto_APPLYJOIN,
		Proto_CANJOINDIRECTLY_NTF,
		Proto_CREDIT_PUNISH_MATCH_BEHAVIOR_NTF,
		Proto_RECRUIT,
		Proto_RECRUIT_NTF,
		Proto_RECRUIT_LIST,
		Proto_RECRUIT_LIST_NTF,
		Proto_STOP_RECRUIT,
		Proto_STOP_RECRUIT_NTF,
		Proto_RECRUIT_GET_INFO,
		Proto_RECRUIT_GET_INFO_NTF,
		Proto_ACTIVATEOWNER,
		Proto_CHANGEOWNERACTIVESTATUS_NTF,
		Proto_ADMIN_MODIFY_GSKOLWHITELIST,
		Proto_ADMIN_CREATE_ESPORTS_ROOM_SPECTATOR,
		Proto_BP_SKILL_OPERATE,
		Proto_BP_SKILL_OPERATE_NTF,
		Proto_BP_GRAB_SKILL,
		Proto_BP_GRAB_SKILL_NTF,
		Proto_BP_GRAB_SKILL_RESPONSE,
		Proto_BP_GRAB_SKILL_RESPONSE_NTF,
		Proto_BP_GRAB_SKILL_RESULT_NTF,
		Proto_BP_EXCHANGE_SKILL,
		Proto_BP_EXCHANGE_SKILL_NTF,
		Proto_BP_ECHANGE_SKILL_RESPONSE,
		Proto_BP_ECHANGE_SKILL_RESPONSE_NTF,
		Proto_BP_ECHANGE_SKILL_RESULT_NTF,
		Proto_BP_ADJUST_LOADOUT,
		Proto_BP_PHASE_START_NTF,
		Proto_BP_TURN_CHANGE_NTF,
		Proto_BP_ADJUST_LOADOUT_NTF,
		Proto_ADMIN_DISMISS_WORKSHOP_ROOM,
		Proto_ADMIN_DEBUG_ROOM_MATCHMAKING,
		Proto_WORKSHOP_HALFWAY_JOIN_CHECK,
		Proto_WORKSHOP_HALFWAY_JOIN_CHECK_NTF,
		Proto_WORKSHOP_HALFWAY_JOIN,
		Proto_WORKSHOP_HALFWAY_JOIN_NTF,
		Proto_WORKSHOP_HALFWAY_INVITE,
		Proto_WORKSHOP_HALFWAY_INVITE_NTF
	}

	public enum ErrCode
	{
		ErrCode_SUSS,
		ErrCode_NOROOM,
		ErrCode_REACHMAXMEMBERS,
		ErrCode_REACHMAXSPECTATORS,
		ErrCode_ALREADYINROOM,
		ErrCode_NOTINROOM,
		ErrCode_ROOMINGAME,
		ErrCode_ROOMNOTINGAME,
		ErrCode_CANNOTCREATEROOM,
		ErrCode_NOGAMESERVERAVAILABLE,
		ErrCode_INVALIDCODE,
		ErrCode_CANNOTKICK,
		ErrCode_NOTOWNER,
		ErrCode_GENMATCHIDFAIL,
		ErrCode_LOGINGAMESERVERTIMEOUT,
		ErrCode_CREATEROOMFAIL,
		ErrCode_JOININVALIDPLAYERCNT,
		ErrCode_DIRTYWORD,
		ErrCode_SEATOCCUPIED,
		ErrCode_CANNOTSWITCHSEAT,
		ErrCode_INVALIDMEMBERNUM,
		ErrCode_NOTENOUGHROOMCARD,
		ErrCode_INVALIDOPTIONS,
		ErrCode_CANNOTINVITESELF,
		ErrCode_INVALIDROOMTYPE,
		ErrCode_INVITEEALREADYINGROUP,
		ErrCode_INVITEEALREADYINROOM,
		ErrCode_INVITEEALREADYINGAME,
		ErrCode_INVITEEALREADYOFFLINE,
		ErrCode_NOTENOUGHMEMEBERS,
		ErrCode_REACHMAXINGAMEROOMNUMLIMIT,
		ErrCode_NEGATIVEGEMS,
		ErrCode_ANTIADDICTIONBAN,
		ErrCode_ROOMCENTERNOTREADY,
		ErrCode_INVITEEALREADYINTRAINING,
		ErrCode_MAPINVALIDFORSOMEMEMBERS,
		ErrCode_REOPENIDNOTEXISTS,
		ErrCode_EMULATORCHECKFAILED,
		ErrCode_GROUPOCCUPIED,
		ErrCode_REACHMAXBATCHROOMNUMLIMIT,
		ErrCode_NOCREATEROLE,
		ErrCode_NOJOINROLE,
		ErrCode_WORKSHOP_UPDATED,
		ErrCode_PLAYERMAPINVALID,
		ErrCode_CREDITSCORECHECKFAILED,
		ErrCode_INVITEEALREADYINSOCIALAREA,
		ErrCode_ROOMMATCHMAKINGNOTOPEN,
		ErrCode_ALREADYINROOMMATCHMAKING,
		ErrCode_ROOMMATCHMAKINGTIMEOUT,
		ErrCode_ROOMMATCHMAKINGFAILED,
		ErrCode_FAIL_TO_FETCH_WORKSHOP_INFO,
		ErrCode_ROOMINMATCHMAKING,
		ErrCode_ROOMNOTINMATCHMAKING,
		ErrCode_ROOMHASCODE,
		ErrCode_NOTINROOMMATCHMAKING,
		ErrCode_ROOMMATCHMAKINGCLOSED,
		ErrCode_INVITEEALREADYINMATCHMAKING,
		ErrCode_LEVELCHECKFAILED,
		ErrCode_REACHMAXCUSTOMDATASTORAGEROOMNUMLIMIT,
		ErrCode_REMINDEE_NOT_IN_ROOM,
		ErrCode_NOT_IN_CLAN,
		ErrCode_CANNOTROOMMATCHMAKINGWITHHACKERTAG,
		ErrCode_REACHMAXMEMBERNUMLIMIT,
		ErrCode_PGCCANNOTOPENMATCHMAKING,
		ErrCode_UGC_ANTIHACK,
		ErrCode_HACKERSPECTATE,
		ErrCode_EMULATORSPECTATE,
		ErrCode_SPECTATEHACKER,
		ErrCode_SPECTATEEMULATOR,
		ErrCode_DISABLESPECTATE,
		ErrCode_SPECTATEPLAYERNOTINGAME,
		ErrCode_SPECTATORNUMLIMIT,
		ErrCode_AFKPUNISH,
		ErrCode_INVALIDPARTICIPANT,
		ErrCode_LEAVEORIGINALROOMFAILED,
		ErrCode_SPECTATEROOMOB,
		ErrCode_SPECTATEROOMHASCODE,
		ErrCode_NOTSOLEACTIVESKILL,
		ErrCode_INVALIDCOUNTDOWNSECS,
		ErrCode_INVALIDROOMQRCODE,
		ErrCode_INVALIDMAPVERSION,
		ErrCode_CREDIT_PUNISH_MATCH_BEHAVIOR,
		ErrCode_ROOM_TYPE_NOT_SUPPORT_RECRUIT,
		ErrCode_RECRUIT_ROOM_NOT_FOUND,
		ErrCode_RECRUIT_CODE_NOT_MATCH,
		ErrCode_BP_INVALID_OPERATION,
		ErrCode_BP_INVALID_SKILL_ID,
		ErrCode_BP_SKILL_UNAVAILABLE,
		ErrCode_BP_SKILL_ALREADY_BANNED,
		ErrCode_BP_ROOM_NOT_IN_BP,
		ErrCode_BP_CHANNEL_FULL,
		ErrCode_BP_SKILL_NUM_LIMIT,
		ErrCode_BP_ACTIVE_SKILL_NUM_LIMIT,
		ErrCode_BP_DONT_HAVE_PET_SKILL,
		ErrCode_BP_DONT_HAVE_LOADOUT,
		ErrCode_BP_SKILL_DUPLICATED,
		ErrCode_BP_UNSUPPORTED_GROUP_MODE,
		ErrCode_BP_DONT_HAVE_PET,
		ErrCode_NOT_FRIEND,
		ErrCode_WORKSHOP_HALFWAY_JOIN_CLOSED,
		ErrCode_WORKSHOP_HALFWAY_IN_SPECTATE,
		ErrCode_CROSSPLATFORMRECONNECTIONNOTQUALIFIED
	}

	public enum Type
	{
		Type_NONE = 0,
		Type_CASUAL = 1,
		Type_LEAGUE_NORMAL = 2,
		Type_LEAGUE_BATCH = 6,
		Type_WEREWOLVES = 7,
		Type_WORKSHOP = 8,
		Type_RUSHING_PETS = 9,
		Type_CLAN = 10,
		Type_ESPORTS = 11
	}

	public enum TabType
	{
		TabType_NONE,
		TabType_NORMAL,
		TabType_LEAGUE,
		TabType_WEREWOLVES,
		TabType_WORKSHOP,
		TabType_RUSHING_PETS,
		TabType_CLAN,
		TabType_ESPORTS
	}

	public enum PlayerRole
	{
		PlayerRole_NONE,
		PlayerRole_MEMBER,
		PlayerRole_SPECTATOR
	}

	public enum PlayerState
	{
		PlayerState_IDLE,
		PlayerState_LOADING,
		PlayerState_INGAME,
		PlayerState_INGAME_CAN_RECONNECT,
		PlayerState_BP
	}

	public enum PlayerPatchOptionalResStatus
	{
		PlayerPatchOptionalResStatus_NONE,
		PlayerPatchOptionalResStatus_LACK,
		PlayerPatchOptionalResStatus_START
	}

	public enum State
	{
		State_IDLE,
		State_INGAME,
		State_LOADING,
		State_MATCHMAKING,
		State_BP
	}

	public enum DismissReason
	{
		DismissReason_NONE,
		DismissReason_NORMAL,
		DismissReason_OFFLINE,
		DismissReason_TIMEOUT,
		DismissReason_ADMIN,
		DismissReason_WORKSHOP_LOADING_TIMEOUT,
		DismissReason_WORKSHOP_AUTO_CREATE_ROOM_END_MATCH,
		DismissReason_ADVANCED_ROOM_KEEP_TIMEOUT,
		DismissReason_OWNER_BE_PUNISHED,
		DismissReason_ESPORTS
	}

	public enum UpdateRoomEvent
	{
		UpdateRoomEvent_NONE,
		UpdateRoomEvent_INIT,
		UpdateRoomEvent_SEND_ALL_ROOMS,
		UpdateRoomEvent_STATE,
		UpdateRoomEvent_OPTIONS,
		UpdateRoomEvent_MEMBER_NUM,
		UpdateRoomEvent_DISMISS_ROOM,
		UpdateRoomEvent_CREATE_ROOM,
		UpdateRoomEvent_EMPTY,
		UpdateRoomEvent_ENOUGH_ROOM_CARD,
		UpdateRoomEvent_OWNER_ONLINE,
		UpdateRoomEvent_OPEN_MATCHMAKING,
		UpdateRoomEvent_CLOSE_MATCHMAKING,
		UpdateRoomEvent_MATCHMAKING_SUSS,
		UpdateRoomEvent_CHANGE_ROOM,
		UpdateRoomEvent_OWNER_ACTIVE
	}

	public enum RemindType
	{
		RemindType_NONE,
		RemindType_CAPTAIN_START
	}

	public enum WorkshopRoomLabel
	{
		WorkshopRoomLabel_NONE,
		WorkshopRoomLabel_CUSTOM_DATA_STORAGE,
		WorkshopRoomLabel_AUTO_CREATED,
		WorkshopRoomLabel_HALFWAY_SUBMIT
	}

	public enum Class
	{
		Class_NORMAL,
		Class_ADVANCED
	}

	public enum RecruitListType
	{
		RecruitListType_AUTO_REFRESH,
		RecruitListType_MANUAL_REFRESH
	}

	public enum JoinChannelType
	{
		JoinChannelType_NONE,
		JoinChannelType_DEFAULT,
		JoinChannelType_WORLD,
		JoinChannelType_GUILD,
		JoinChannelType_RECRUIT
	}

	public enum BPOperateType
	{
		OP_NONE,
		OP_PRE_PICK,
		OP_PRE_BAN,
		OP_BAN,
		OP_PICK,
		OP_ASK_BAN
	}

	public enum BPPhase
	{
		PHASE_NONE,
		PHASE_PRE_SELECT,
		PHASE_BAN,
		PHASE_SHOW_BAN,
		PHASE_PICK,
		PHASE_ADJUST
	}
}
